
version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: purchase-order-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - supabase
    networks:
      - app-network

  # Supabase Local (para desenvolvimento)
  supabase:
    image: supabase/postgres:15.1.0.25
    container_name: supabase-local
    ports:
      - "54321:5432"  # PostgreSQL port
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  supabase-data:
    driver: local
